language: r
cache: packages
r:
  - release

r_check_args: --as-cran --compact-vignettes=both

r_build_args: --compact-vignettes=both

before_install:
  - tlmgr install tikz-cd sansmath hobby contour
  - sudo add-apt-repository -y ppa:moti-p/cc
  - sudo apt-get update
  - sudo apt-get -y --reinstall install ghostscript
  
warnings_are_errors: true

sudo: false

notifications:
  email:
    on_success: change
    on_failure: always


os:
  - linux



